export const droppableFlags = {
  removeTopLevelAwaits: "removeTopLevelAwaits",
  removeObservableWithValueValidations: "removeObservableWithValueValidations",
  removeFunctionAndClassJSXElements: "removeFunctionAndClassJSXElements",
  removeNilJSXElements: "removeNilJSXElements",
  removeNodeJSXElements: "removeNodeJSXElements",
  removeDOMJSXElements: "removeDOMJSXElements",
  removeArrayJSXElements: "removeArrayJSXElements",
  removeFragmentJSXElements: "removeFragmentJSXElements",
  removeDeepBindingObservableObjects: "removeDeepBindingObservableObjects",
  removeBooleanAndObjectAttributes: "removeBooleanAndObjectAttributes",
  removeVirtualFragmentOnNonProxiedArrays: "removeVirtualFragmentOnNonProxiedArrays",
  removeSpecialAttributes: "removeSpecialAttributes",
  removeSupportForNonHTMLNamespacesAndBuiltInElements:
    "removeSupportForNonHTMLNamespacesAndBuiltInElements",
  removeBindFunction: "removeBindFunction",
  removeObservablesGarbageCollection: "removeObservablesGarbageCollection",
  removePropertiesSupport: "removePropertiesSupport",
  removeFunctionObservablesSupport: "removeFunctionObservablesSupport",
  removeSwapValidations: "removeSwapValidations",
};
