export { h } from './LSElement/h';
export { AutonomousCustomElement } from './LSElement/decorators/AutonomousCustomElement';
export { CustomizedBuiltInElement } from './LSElement/decorators/CustomizedBuiltInElement';
export { Attribute, Property, Child, EventDispatcher, Redux } from './LSElement/decorators/PropertyDecorators';
export type { LSCustomElement } from './LSElement/types';
export type { HTMLAttributes } from './LSElement/h/JSXBase';
export { CustomEventDispatcher } from './LSElement/classes/CustomEventDispatcher';
export { IdGenerator } from './LSElement/classes/IdGenerator';
import './LSElement/h/global';
import './LSElement/h/external';
