import "./michijs/polyfill";
export * from "./michijs/classes";
export * from "./michijs/h";
export * from "./michijs/constants";
export * from "./michijs/trustedTypes";
export * from "./michijs/routing";
export * from "./michijs/types";
export * from "./michijs/DOM";
export * from "./michijs/i18n";
export * from "./michijs/generated/htmlType";
export * from "./michijs/customElements";
export * from "./michijs/css";
export * from "./michijs/utils";
export * from "./michijs/components";
export * from "./michijs/hooks";
import "./michijs/generated/JSX";
import "./michijs/navigation-api-types";
