name: "Lint"

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: michijs/.github/.github/workflows/lint.yml@main
    name: "Run lint"
    secrets:
      GITHUB_TOKEN: ${{ secrets.PAT }}
