name: "Lint"

on: [push, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: michijs/.github/.github/workflows/lint.yml@main
    name: "Run lint"
    secrets: inherit
  run-tests:
    uses: ./.github/workflows/tests.yml
    secrets: inherit
    needs: lint
    with:
      ref: lint/${{ github.head_ref || github.ref_name }}
