name: Lint
on:
  push:
    branches-ignore:
      - 'lint/**'
      - 'michijs-dependabot*'
      - 'dependabot*'
      - 'production'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        uses: michijs/.github/.github/actions/lint@main
        with:
          GITHUB_TOKEN: ${{ secrets.PAT }}
