name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      release-notes:
        description: "Release notes"
        type: string
      release-notes-path:
        description: "Release notes path"
        type: string
  push:
    branches:
      - master
    paths:
      - '/src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    name: 'Call Workflow'
    uses: "michijs/.github/.github/workflows/release-package.yml@main"
    with:
      release-notes-path: ${{ github.event.inputs.release-notes-path }}
      release-type: ${{ github.event.inputs.release-type || 'prerelease' }}
      release-notes: ${{ github.event.inputs.release-notes || 'Automatic release' }}
    secrets: inherit
  Deploy-docs:
    name: "Deploy docs"
    runs-on: ubuntu-latest
    if: startsWith(github.event.inputs.release-type || 'prerelease', 'pre') != true
    needs: call-workflow
    steps: 
      - name: "Call github script"
        uses: ./update-docs.yml
        with:
          github-token: ${{ secrets.PAT }}
