name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      release-notes:
        description: "Release notes"
        type: string
      release-notes-path:
        description: "Release notes path"
        type: string
  workflow_run:
    workflows: ["Tests"]
    branches: [master]
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow:
    name: 'Call Workflow'
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    uses: "michijs/.github/.github/workflows/release-package.yml@main"
    with:
      release-notes-path: ${{ github.event.inputs.release-notes-path }}
      release-type: ${{ github.event.inputs.release-type || 'prerelease' }}
      release-notes: ${{ github.event.inputs.release-notes || 'Automatic release' }}
    secrets: inherit
